version: "2.1"
services:
  spark:
    image: apache/spark:v3.3.1
    container_name: spark
    user: root
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - "./data:/tmp/feathub-data"
    command:
      - bash
      - -c
      - "/opt/spark/sbin/start-master.sh && /opt/spark/sbin/start-worker.sh spark://spark:7077; while true; do sleep 10; done"
