name: Build And Test
on:
  schedule:
    - cron: '0 20 * * *'
  push:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  run-examples:
    runs-on: ubuntu-20.04
    if: github.repository == 'flink-extended/feathub-examples' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Run example
        run: bash tools/ci/run_tests.sh
      - name: Debug with tmate
        if: ${{ failure() && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
