name: Build And Test
on:
  schedule:
    - cron: '0 20 * * *'
  push:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      target_package:
        type: string
        description: 'Target FeatHub Python package (See FEATHUB_PACKAGE argument in ./docker/Dockerfile for more details)'
        required: false
        default: ''
jobs:
  run-examples:
    runs-on: ubuntu-20.04
    if: github.repository == 'flink-extended/feathub-examples' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v3
      - name: start mimnikube
        uses: medyagh/setup-minikube@latest
        with:
          cpus: 2
          memory: 4000m
      - name: Set up python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Run example
        run: bash tools/ci/run_tests.sh ${{ inputs.target_package }}
      - name: Debug with tmate
        if: ${{ failure() && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
